[env.production]
name = "chorly"
compatibility_date = "2024-03-15"
pages_build_output_dir = "dist"

[env.production.vars]
NODE_ENV = "production"

[[env.production.d1_databases]]
binding = "DB"
database_name = "chorly-db"
database_id = "placeholder"

[build]
command = "npm run build"